-- KVKK rıza alanları
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS kvkk_approved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS kvkk_approved_at TIMESTAMP;

ALTER TABLE reports ADD COLUMN IF NOT EXISTS kvkk_approved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS kvkk_approved_at TIMESTAMP;
