-- V64__add_soft_delete_columns.sql
-- Add deleted column to entities requiring soft delete support

ALTER TABLE reports ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE municipality_outages ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE municipality_events ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bus_routes ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE municipality_surveys ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE export_schedules ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE municipality_announcements ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE blood_search_ads ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE lost_pet_ads ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE item_donation_ads ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
